# PLEASE RELOAD AFTER ANY CHANGE
mobs:
- ==: MobsData
  CustomSpawn: true
  AllSpawn: true
  EggSpawn: true
  NaturalSpawn: true
  SpawnerSpawn: true
  Name: ELDER_GUARDIAN
- ==: MobsData
  CustomSpawn: true
  AllSpawn: true
  EggSpawn: true
  NaturalSpawn: true
  SpawnerSpawn: true
  Name: WITHER_SKELETON
- ==: MobsData
  CustomSpawn: true
  AllSpawn: true
  EggSpawn: true
  NaturalSpawn: true
  SpawnerSpawn: true
  Name: STRAY
- ==: MobsData
  CustomSpawn: true
  AllSpawn: true
  EggSpawn: true
  NaturalSpawn: true
  SpawnerSpawn: true
  Name: HUSK
- ==: MobsData
  CustomSpawn: true
  AllSpawn: true
  EggSpawn: true
  NaturalSpawn: true
  SpawnerSpawn: true
  Name: ZOMBIE_VILLAGER
- ==: MobsData
  CustomSpawn: true
  AllSpawn: true
  EggSpawn: true
  NaturalSpawn: true
  SpawnerSpawn: true
  Name: SKELETON_HORSE
- ==: MobsData
  CustomSpawn: true
  AllSpawn: true
  EggSpawn: true
  NaturalSpawn: true
  SpawnerSpawn: true
  Name: ZOMBIE_HORSE
- ==: MobsData
  CustomSpawn: true
  AllSpawn: true
  EggSpawn: true
  NaturalSpawn: true
  SpawnerSpawn: true
  Name: DONKEY
- ==: MobsData
  CustomSpawn: true
  AllSpawn: true
  EggSpawn: true
  NaturalSpawn: true
  SpawnerSpawn: true
  Name: MULE
- ==: MobsData
  CustomSpawn: true
  AllSpawn: true
  EggSpawn: true
  NaturalSpawn: true
  SpawnerSpawn: true
  Name: EVOKER
- ==: MobsData
  CustomSpawn: true
  AllSpawn: true
  EggSpawn: true
  NaturalSpawn: true
  SpawnerSpawn: true
  Name: VEX
- ==: MobsData
  CustomSpawn: true
  AllSpawn: true
  EggSpawn: true
  NaturalSpawn: true
  SpawnerSpawn: true
  Name: VINDICATOR
- ==: MobsData
  CustomSpawn: true
  AllSpawn: true
  EggSpawn: true
  NaturalSpawn: true
  SpawnerSpawn: true
  Name: CREEPER
- ==: MobsData
  CustomSpawn: true
  AllSpawn: true
  EggSpawn: true
  NaturalSpawn: true
  SpawnerSpawn: true
  Name: SKELETON
- ==: MobsData
  CustomSpawn: true
  AllSpawn: true
  EggSpawn: true
  NaturalSpawn: true
  SpawnerSpawn: true
  Name: SPIDER
- ==: MobsData
  CustomSpawn: true
  AllSpawn: true
  EggSpawn: true
  NaturalSpawn: true
  SpawnerSpawn: true
  Name: GIANT
- ==: MobsData
  CustomSpawn: true
  AllSpawn: true
  EggSpawn: true
  NaturalSpawn: true
  SpawnerSpawn: true
  Name: ZOMBIE
- ==: MobsData
  CustomSpawn: true
  AllSpawn: true
  EggSpawn: true
  NaturalSpawn: true
  SpawnerSpawn: true
  Name: SLIME
- ==: MobsData
  CustomSpawn: true
  AllSpawn: true
  EggSpawn: true
  NaturalSpawn: true
  SpawnerSpawn: true
  Name: GHAST
- ==: MobsData
  CustomSpawn: true
  AllSpawn: true
  EggSpawn: true
  NaturalSpawn: true
  SpawnerSpawn: true
  Name: PIG_ZOMBIE
- ==: MobsData
  CustomSpawn: true
  AllSpawn: true
  EggSpawn: true
  NaturalSpawn: true
  SpawnerSpawn: true
  Name: ENDERMAN
- ==: MobsData
  CustomSpawn: true
  AllSpawn: true
  EggSpawn: true
  NaturalSpawn: true
  SpawnerSpawn: true
  Name: CAVE_SPIDER
- ==: MobsData
  CustomSpawn: true
  AllSpawn: true
  EggSpawn: true
  NaturalSpawn: true
  SpawnerSpawn: true
  Name: SILVERFISH
- ==: MobsData
  CustomSpawn: true
  AllSpawn: true
  EggSpawn: true
  NaturalSpawn: true
  SpawnerSpawn: true
  Name: BLAZE
- ==: MobsData
  CustomSpawn: true
  AllSpawn: true
  EggSpawn: true
  NaturalSpawn: true
  SpawnerSpawn: true
  Name: MAGMA_CUBE
- ==: MobsData
  CustomSpawn: true
  AllSpawn: true
  EggSpawn: true
  NaturalSpawn: true
  SpawnerSpawn: true
  Name: ENDER_DRAGON
- ==: MobsData
  CustomSpawn: true
  AllSpawn: true
  EggSpawn: true
  NaturalSpawn: true
  SpawnerSpawn: true
  Name: WITHER
- ==: MobsData
  CustomSpawn: true
  AllSpawn: true
  EggSpawn: true
  NaturalSpawn: true
  SpawnerSpawn: true
  Name: BAT
- ==: MobsData
  CustomSpawn: true
  AllSpawn: true
  EggSpawn: true
  NaturalSpawn: true
  SpawnerSpawn: true
  Name: WITCH
- ==: MobsData
  CustomSpawn: true
  AllSpawn: true
  EggSpawn: true
  NaturalSpawn: true
  SpawnerSpawn: true
  Name: ENDERMITE
- ==: MobsData
  CustomSpawn: true
  AllSpawn: true
  EggSpawn: true
  NaturalSpawn: true
  SpawnerSpawn: true
  Name: GUARDIAN
- ==: MobsData
  CustomSpawn: true
  AllSpawn: true
  EggSpawn: true
  NaturalSpawn: true
  SpawnerSpawn: true
  Name: SHULKER
- ==: MobsData
  CustomSpawn: true
  AllSpawn: true
  EggSpawn: true
  NaturalSpawn: true
  SpawnerSpawn: true
  Name: PIG
- ==: MobsData
  CustomSpawn: true
  AllSpawn: true
  EggSpawn: true
  NaturalSpawn: true
  SpawnerSpawn: true
  Name: SHEEP
- ==: MobsData
  CustomSpawn: true
  AllSpawn: true
  EggSpawn: true
  NaturalSpawn: true
  SpawnerSpawn: true
  Name: COW
- ==: MobsData
  CustomSpawn: true
  AllSpawn: true
  EggSpawn: true
  NaturalSpawn: true
  SpawnerSpawn: true
  Name: CHICKEN
- ==: MobsData
  CustomSpawn: true
  AllSpawn: true
  EggSpawn: true
  NaturalSpawn: true
  SpawnerSpawn: true
  Name: SQUID
- ==: MobsData
  CustomSpawn: true
  AllSpawn: true
  EggSpawn: true
  NaturalSpawn: true
  SpawnerSpawn: true
  Name: WOLF
- ==: MobsData
  CustomSpawn: true
  AllSpawn: true
  EggSpawn: true
  NaturalSpawn: true
  SpawnerSpawn: true
  Name: MUSHROOM_COW
- ==: MobsData
  CustomSpawn: true
  AllSpawn: true
  EggSpawn: true
  NaturalSpawn: true
  SpawnerSpawn: true
  Name: SNOWMAN
- ==: MobsData
  CustomSpawn: true
  AllSpawn: true
  EggSpawn: true
  NaturalSpawn: true
  SpawnerSpawn: true
  Name: OCELOT
- ==: MobsData
  CustomSpawn: true
  AllSpawn: true
  EggSpawn: true
  NaturalSpawn: true
  SpawnerSpawn: true
  Name: IRON_GOLEM
- ==: MobsData
  CustomSpawn: true
  AllSpawn: true
  EggSpawn: true
  NaturalSpawn: true
  SpawnerSpawn: true
  Name: HORSE
- ==: MobsData
  CustomSpawn: true
  AllSpawn: true
  EggSpawn: true
  NaturalSpawn: true
  SpawnerSpawn: true
  Name: RABBIT
- ==: MobsData
  CustomSpawn: true
  AllSpawn: true
  EggSpawn: true
  NaturalSpawn: true
  SpawnerSpawn: true
  Name: POLAR_BEAR
- ==: MobsData
  CustomSpawn: true
  AllSpawn: true
  EggSpawn: true
  NaturalSpawn: true
  SpawnerSpawn: true
  Name: LLAMA
- ==: MobsData
  CustomSpawn: true
  AllSpawn: true
  EggSpawn: true
  NaturalSpawn: true
  SpawnerSpawn: true
  Name: PARROT
- ==: MobsData
  CustomSpawn: true
  AllSpawn: true
  EggSpawn: true
  NaturalSpawn: true
  SpawnerSpawn: true
  Name: VILLAGER
- ==: MobsData
  CustomSpawn: true
  AllSpawn: true
  EggSpawn: true
  NaturalSpawn: true
  SpawnerSpawn: true
  Name: TURTLE
- ==: MobsData
  CustomSpawn: true
  AllSpawn: false
  EggSpawn: true
  NaturalSpawn: true
  SpawnerSpawn: true
  Name: PHANTOM
- ==: MobsData
  CustomSpawn: true
  AllSpawn: true
  EggSpawn: true
  NaturalSpawn: true
  SpawnerSpawn: true
  Name: COD
- ==: MobsData
  CustomSpawn: true
  AllSpawn: true
  EggSpawn: true
  NaturalSpawn: true
  SpawnerSpawn: true
  Name: SALMON
- ==: MobsData
  CustomSpawn: true
  AllSpawn: true
  EggSpawn: true
  NaturalSpawn: true
  SpawnerSpawn: true
  Name: PUFFERFISH
- ==: MobsData
  CustomSpawn: true
  AllSpawn: true
  EggSpawn: true
  NaturalSpawn: true
  SpawnerSpawn: true
  Name: TROPICAL_FISH
- ==: MobsData
  CustomSpawn: true
  AllSpawn: true
  EggSpawn: true
  NaturalSpawn: true
  SpawnerSpawn: true
  Name: DROWNED
- ==: MobsData
  CustomSpawn: true
  AllSpawn: true
  EggSpawn: true
  NaturalSpawn: true
  SpawnerSpawn: true
  Name: DOLPHIN
- ==: MobsData
  CustomSpawn: true
  AllSpawn: true
  EggSpawn: true
  NaturalSpawn: true
  SpawnerSpawn: true
  Name: CAT
- ==: MobsData
  CustomSpawn: true
  AllSpawn: true
  EggSpawn: true
  NaturalSpawn: true
  SpawnerSpawn: true
  Name: PANDA
- ==: MobsData
  CustomSpawn: true
  AllSpawn: true
  EggSpawn: true
  NaturalSpawn: true
  SpawnerSpawn: true
  Name: PILLAGER
- ==: MobsData
  CustomSpawn: true
  AllSpawn: true
  EggSpawn: true
  NaturalSpawn: true
  SpawnerSpawn: true
  Name: RAVAGER
- ==: MobsData
  CustomSpawn: true
  AllSpawn: true
  EggSpawn: true
  NaturalSpawn: true
  SpawnerSpawn: true
  Name: TRADER_LLAMA
- ==: MobsData
  CustomSpawn: true
  AllSpawn: true
  EggSpawn: true
  NaturalSpawn: true
  SpawnerSpawn: true
  Name: WANDERING_TRADER
- ==: MobsData
  CustomSpawn: true
  AllSpawn: true
  EggSpawn: true
  NaturalSpawn: true
  SpawnerSpawn: true
  Name: FOX
