# Rifle's Chair plugin by Rifle D. Luffy
# Version 6.0
# #=============[Seat Configuration]=============##
# stair-seating-position: The exact positions of where the armorstand spawns on a stair; default 0.35,0.3,0.5
# slab-seating-position: The exact positions of where the armorstand spawns on a slab; default 0.5,0.3,0.5
# carpet-seating-position: The exact positions of where the armorstand spawns on a carpet; default 0.5,-0.15,0.5
# be careful when playing around with this feature!
# in the format x,y,z where...
# x is forward
# y is up
# z is sideways (positive z is to the right, negative z is the left)
stair-seating-position: 0.5,0.3,0.5
slab-seating-positiong: 0.5,0.3,0.5
carpet-seating-position: 0.5,-0.15,0.5
disable-update-message-if-on-latest: false
disable-update-messages: false
exit-seat-where-facing: false
allow-trap-door-chairs: true
require-empty-hand: false
max-distance: 2
max-item-count-to-sit: -1
require-signs-at-end: false
eject-player-on-damage: false
minimum-eject-damage: 2
face-attacker-when-ejected: false
toss-player: false
toss-velocity: 0.5
scale-toss-velocity: true
velocity-scale-factor: 2
regen-when-sitting: true
regen-potency: 0
allow-custom-messages: false
priority-on-if-has-perm: true
allowed-chairs:
- ALL_STAIRS
- ALL_SLABS
- ALL_CARPETS
blacklisted-chairs: []
disabled-worlds: []
