Update: false  

Tab:
  Enable: true
  Cooldown: 5
  #单位:秒
  Tab: "%deluxetags_tag% %player_name%"
Tablist:
  Enable: true
  Cooldown: 5
  #单位:秒
  Header: |-
    &7
    &7欢迎您，&b%player_name%&f来到puresky服务器
    &7
  Footer: |-
    &7
    &e您的称号是&r:%deluxetags_tag%
    &f您的丢人次数{死亡次数}:&e%statistic_deaths%&f次
    &f距离上次死亡已经过了:&e%statistic_minutes_since_death%&f分钟
    &f您总共挖了:
    &f%statistic_mine_block%方块
    &c目前服务器的运行状态{20为满}:&9%server_tps_1%
    &e目前服务器总共实体数目{极其影响性能}:&5%server_total_entities%
    &3您的总共游戏时间:&r%statistic_hours_played%小时
    &3您退出游戏&f%statistic_leave_game%&f次了
    &7
