# DeluxeTags version: 1.7.1 Main Configuration
# 
# Create your tags using the following format:
# 
# deluxetags:
#   VIP: 
#     order: 1
#     tag: '&7[&eVIP&7]'
#     description: 'This tag is awarded by getting VIP'
# 
# Placeholders for your DeluxeChat formats config:
# 
# %deluxetags_identifier% - display the players active tag identifier
# %deluxetags_tag% - display the players active tag
# %deluxetags_description% - display the players active tag description
# %deluxetags_amount% - display the amount of tags a player has access to
# 
# Placeholders for your essentials/chat handling formats config:
# 
# {deluxetags_identifier} - display the players active tag identifier
# {deluxetags_tag} - display the players active tag
# {deluxetags_description} - display the players active tag description
# {deluxetags_amount} - display the amount of tags a player has access to
force_tags: false
check_updates: true
deluxe_chat: false
format_chat:
  enabled: true
  format: '{deluxetags_tag} <%1$s> %2$s'
gui:
  name: '&6Available tags&f: &6%deluxetags_amount%'
  tag_select_item:
    material: NAME_TAG
    data: 0
    displayname: '&6Tag&f: &6%deluxetags_identifier%'
    lore:
    - '%deluxetags_tag%'
    - '%deluxetags_description%'
  divider_item:
    material: STAINED_GLASS_PANE
    data: 15
    displayname: ''
    lore: []
  has_tag_item:
    material: SKULL_ITEM
    data: 3
    displayname: '&eCurrent tag&f: &6%deluxetags_identifier%'
    lore:
    - '%deluxetags_tag%'
    - Click to remove your current tag
  no_tag_item:
    material: SKULL_ITEM
    data: 3
    displayname: '&cYou don''t have a tag set!'
    lore:
    - '&7Click a tag above to select one!'
  exit_item:
    material: IRON_DOOR
    data: 0
    displayname: '&cClick to exit'
    lore:
    - '&7Exit the tags menu'
deluxetags:
  example:
    order: 1
    tag: '&8[&bDeluxeTags&8]'
    description: '&cAwarded for using DeluxeTags!'
  建筑比赛参与者:
    order: 2
    tag: '&b[&c建筑比赛参与者&b]'
    description: '&f'
  绯音天华:
    order: 3
    tag: '&b[&e绯音天华&b]'
    description: '&f'
  邺水朱华:
    order: 4
    tag: '&b[&e邺水朱华&b]'
    description: '&f'
  屋顶上的老司机:
    order: 5
    tag: '&b[&e屋顶上的老司机&b]'
    description: '&f'
  SVIP:
    order: 6
    tag: '&b[&eSVIP&b]'
    description: '&f'
  远坂家的大女婿:
    order: 7
    tag: '&b[&e远&4坂&6家&2的&b大&d女&1婿&b]'
    description: '&f'
  屑腐竹:
    order: 8
    tag: '&b[&e屑腐竹&b]'
    description: '&f'
  bug发现者/反对党:
    order: 9
    tag: '&b[&ebug发现者/反对党&b]'
    description: '&f'
  薇尔莉特·伊芙加登:
    order: 10
    tag: '&b[&5薇尔莉特·伊芙加登&b]'
    description: '&f'
  憨憨:
    order: 11
    tag: '&b[&e憨憨&b]'
    description: '&f'
  '*大逃杀比赛参与者*':
    order: 12
    tag: '&b[&e*大逃杀比赛参与者*&b]'
    description: '&f'
  '*大逃杀比赛第一名*':
    order: 13
    tag: '&b[&e*&5大&9逃&1杀&3比&2赛&c第一名&e*&b]'
    description: '&f'
  保守党:
    order: 14
    tag: '&b[&e保守党&b]'
    description: '&f'
  缱绻倚明月:
    order: 15
    tag: '&b[&e缱绻倚明月&b]'
    description: '&f'
